"""empty message

Revision ID: ca61755dfdec
Revises: 11e9230e61c9
Create Date: 2022-09-08 15:03:54.065127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca61755dfdec'
down_revision = '11e9230e61c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('rsa_signature', sa.String(length=256), nullable=True))
    op.drop_column('victim_users', '_rsa_e')
    op.drop_column('victim_users', '_rsa_q')
    op.drop_column('victim_users', '_rsa_p')
    op.drop_column('victim_users', '_rsa_d')
    op.drop_column('victim_users', '_rsa_n')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('victim_users', sa.Column('_rsa_n', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('victim_users', sa.Column('_rsa_d', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('victim_users', sa.Column('_rsa_p', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('victim_users', sa.Column('_rsa_q', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('victim_users', sa.Column('_rsa_e', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('entries', 'rsa_signature')
    # ### end Alembic commands ###
