"""empty message

Revision ID: d5f354153c42
Revises: ca61755dfdec
Create Date: 2022-09-08 15:06:11.974024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5f354153c42'
down_revision = 'ca61755dfdec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('victim_users', sa.Column('_rsa_e', sa.String(length=32), nullable=True))
    op.add_column('victim_users', sa.Column('_rsa_d', sa.String(length=256), nullable=True))
    op.add_column('victim_users', sa.Column('_rsa_n', sa.String(length=256), nullable=True))
    op.add_column('victim_users', sa.Column('_rsa_p', sa.String(length=256), nullable=True))
    op.add_column('victim_users', sa.Column('_rsa_q', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('victim_users', '_rsa_q')
    op.drop_column('victim_users', '_rsa_p')
    op.drop_column('victim_users', '_rsa_n')
    op.drop_column('victim_users', '_rsa_d')
    op.drop_column('victim_users', '_rsa_e')
    # ### end Alembic commands ###
